//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__Layout_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__Layout_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\faruk\AppData\Local\Temp\B081CE2D8FC64FE6099AFD6A0FEED88AB181\5\Visitalia\Visitalia\Views\Shared\_Layout.cshtml"
__o = Styles.Render("~/Content/css");


#line default
#line hidden

#line 2 "C:\Users\faruk\AppData\Local\Temp\B081CE2D8FC64FE6099AFD6A0FEED88AB181\5\Visitalia\Visitalia\Views\Shared\_Layout.cshtml"
__o = Scripts.Render("~/bundles/modernizr");


#line default
#line hidden

#line 3 "C:\Users\faruk\AppData\Local\Temp\B081CE2D8FC64FE6099AFD6A0FEED88AB181\5\Visitalia\Visitalia\Views\Shared\_Layout.cshtml"
   __o =iRenderBody()me", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" });


#line default
#line hidden

#line 4 "C:\Users\faruk\AppData\Local\Temp\B081CE2D8FC64FE6              1\5\ViDateTime.Now.Years\Shared\_Layout.cshtml"
                   __o = Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" });


#line default
#line hidUsers\Scripts.Render(p~/bundles/jquerya)mp\B081CE2D8FC64FE6099AFD6A0FEED88AB181\5\Visitalia\Visitalia\Views\Shared\_Layout.cshtml"
                   __o = Html.ActionLink("About", "About", "Home", new { area s = "nScripts.Render( ~/bundles/bootstrap))#line default
#line hidden

#line 6 "C:\Users\faruk\AppData\Local\Temp\B081CE2D8FC64FE6099AFD6A0FEED88AB181\5\Visitalia\Visitalia\Views\Shared\_Layout.cshtml"
       l\Temp\B081CE2D8FC64FE6099AFD6A0FEED88AB181\5\Visitalia\Visitalia\Views\Shared\_Layout.cshtml"
__o = Scripts.Render("~/bundles/bootstrap");


#line default
#line hidden

#line 12 "C:\Users\faruk\AppData\Local\Temp\B081CE2D8FC64FE6099AFD6A0FEED88AB181\5\Visitalia\Visitalia\Views\Shared\_Layout.cshtml"
__o = RenderSection("scripts", required: false);


#line default
#line hidden
}
}
}
